---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app govee2mqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: govee2mqtt
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: mosquitto
      namespace: default
    - name: openebs
      namespace: openebs-system
  values:
    controllers:
      govee2mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/wez/govee2mqtt
              tag: latest@sha256:fe5da030c7dbf3b1107f654bf13e16e5e869d03048e977272c208755a5a21d6c
            env:
              TZ: America/Los_Angeles
              GOVEE_MQTT_HOST: mosquitto.default.svc.cluster.local
              GOVEE_MQTT_PORT: 1883
              GOVEE_TEMPERATURE_SCALE: F
              RUST_LOG_STYLE: always
              #RUST_LOG: govee=trace
            envFrom:
              - secretRef:
                  name: govee2mqtt-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "iot",
            "namespace": "networking",
            "ips": ["10.0.30.7/24"],
            "mac": "c6:07:27:af:fb:55"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: govee2mqtt
        ports:
          http:
            port: 4002
    persistence:
      data:
        existingClaim: *app
