---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-postgres-secret
    template:
      data:
        s3.conf: |
          [global]
          repo2-s3-key={{ .AWS_ACCESS_KEY_ID }}
          repo2-s3-key-secret={{ .AWS_SECRET_ACCESS_KEY }}
        encryption.conf: |
          [global]
          repo2-cipher-pass={{ .ENCRYPTION_KEY }}
        init.sql: |
          \c immich
          BEGIN;
          ALTER DATABASE "immich" OWNER TO "immich";
          CREATE EXTENSION vector CASCADE;
          CREATE EXTENSION earthdistance CASCADE;
          COMMIT;
  dataFrom:
    - extract:
        key: backblaze