---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bluemap
  namespace: &namespace minecraft
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/postgres
  healthCheckExprs:
    - apiVersion: postgres-operator.crunchydata.com/v1beta1
      kind: PostgresCluster
      failed: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'True')
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: crunchy-postgres-operator
      namespace: database
  path: ./kubernetes/apps/minecraft/bluemap/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
