---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app modded
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          modded:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2025.10.0-java21
            env:
              EULA: "true"
              TZ: America/Los_Angeles
              TYPE: "PAPER"
              VERSION: "1.21.8"
              ONLINE_MODE: false
              SERVER_NAME: *app
              DIFFICULTY: easy
              OPS: "Kashall"
              MAX_PLAYERS: 40
              KEEP_INVENTORY: true
              ENABLE_ROLLING_LOGS: true
              ALLOW_FLIGHT: true
              INIT_MEMORY: 1G
              MAX_MEMORY: &max-memory 12G
              MODRINTH_PROJECTS: |
                bluemap
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 2
                memory: *max-memory
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      modded:
        controller: minecraft
        type: LoadBalancer
        annotations:
          # SRV Record is _minecraft._tcp.modded.ok8.sh which points to modded-srv.ok8.sh.
          # MC-Router is getting all of these portforwards to it and when the SRV resolves it points to modded-srv.ok8.sh which is this external server name.
          mc-router.itzg.me/externalServerName: "modded-srv.ok8.sh"
        ports:
          game:
           port: &game-port 25565
          rcon:
           port: &rcon-port 25578
          http:
            port: &web-port 8100
    route:
      modded:
        hostnames: ["modded.ok8.sh"]
        parentRefs:
          - name: external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *web-port
            matches:
              - path:
                 type: PathPrefix
                 value: /
    persistence:
      tmp:
        type: emptyDir
      data:
        existingClaim: *app
        globalMounts:
          - path: /data