---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  storage:
    size: 5Gi
    storageClass: ceph-block

  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  enablePDB: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"

  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: forgejo
        serverName: &currentServer forgejo
