---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: forgejo-pg-credentials
spec:
  deletionPolicy: Delete
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: forgejo-app
  data:
    - match:
        secretKey: &key dbname
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
    - match:
        secretKey: &key host
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
    - match:
        secretKey: &key password
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
    - match:
        secretKey: &key port
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
    - match:
        secretKey: &key uri
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
    - match:
        secretKey: &key user
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
    - match:
        secretKey: &key username
        remoteRef:
          remoteKey: forgejo-pg-credentials
          property: *key
