---
machine:
  type: controlplane
  install:
    image: factory.talos.dev/metal-installer/f0fb8b3a41217b64c81292fbdc81d35a9860c1761b5530c0457f43d2c692aafa:v1.13.2
    diskSelector:
      serial: 50026B76878F13D4
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: puddle
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: sfp0
selector:
  match: mac(link.permanent_addr) == "7c:fe:90:19:f5:00"
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: sfp1
selector:
  match: mac(link.permanent_addr) == "7c:fe:90:19:f5:01"
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links: [sfp0, sfp1]
bondMode: 802.3ad
miimon: 100
updelay: 200
downdelay: 200
xmitHashPolicy: layer3+4
lacpRate: fast
mtu: 9000
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
clientIdentifier: mac
