---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-api-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOME_ASSISTANT_BASE_URL: "http://home-assistant.default.svc.cluster.local:8123"
        HOME_ASSISTANT_TOKEN: "{{ .HOME_ASSISTANT_TOKEN }}"
        HOME_ASSISTANT_LIGHT_GROUP: "{{ .HOME_ASSISTANT_LIGHT_GROUP }}"
  dataFrom:
    - extract:
        key: home-assistant-api
