---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app onepassword
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  dependsOn:
    - name: external-secrets
  path: ./kubernetes/apps/external-secrets/onepassword/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  timeout: 5m
  wait: true