---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    requires:
      vars: ["cluster"]
    cmds:
      - flux --context {{.cluster}} reconcile -n flux-system kustomization home-kubernetes --with-source

  hr-restart:
    desc: Restart all failed Helm Releases
    requires:
      vars: ["cluster"]
    cmds:
      - kubectl --context {{.cluster}} get hr --all-namespaces | grep False | awk '{print $2, $1}' | xargs -l bash -c 'flux --context {{.cluster}} suspend hr $0 -n $1'
      - kubectl --context {{.cluster}} get hr --all-namespaces | grep False | awk '{print $2, $1}' | xargs -l bash -c 'flux --context {{.cluster}} resume hr $0 -n $1'
