---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ok8-sh
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ok8-sh
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ok8-sh:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/kashalls/kashall.dev
              tag: 1.0.1
            env:
              NUXT_PUBLIC_SITE_URL: "https://ok8.sh"
              NUXT_PUBLIC_USER_ID: "201077739589992448"
              NUXT_PUBLIC_GITHUB: "kashalls"
              NUXT_CONTACT_TO: "noc@ok8.sh"
            envFrom:
              - secretRef:
                  name: ok8-sh-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 750m
                memory: 1G
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: ok8-sh
        ports:
          http:
            port: 3000
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames: ["landing.ok8.sh", "ok8.sh"]
        parentRefs:
          - name: external
            namespace: networking
            sectionName: https
      fallback:
        parentRefs:
          - name: external
            namespace: networking
            sectionName: https
          - name: internal
            namespace: networking
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /gateway
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
