---
apiVersion: v1
kind: Service
metadata:
  name: kube-vip
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s.ok8.sh
    lbipam.cilium.io/ips: 10.0.20.2
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - port: 6443