---
groups:
  - name: plex-next
    rules:
      - alert: PlexNextDatabaseIsBusy
        expr: |
          sum by (app) (count_over_time({app="plex-next"} |~ "(?i)retry busy DB"[5m])) > 0
        for: 5m
        annotations:
          summary: >-
            {{ $labels.app }} is experiencing database issues
        labels:
          severity: critical
