---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trmnl
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: trmnl-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # TRMNL private plugin webhook URLs.
        TRMNL_TEXT_WEBHOOK_URL: "{{ .TRMNL_TEXT_WEBHOOK_URL }}"
        TRMNL_IMAGE_WEBHOOK_URL: "{{ .TRMNL_IMAGE_WEBHOOK_URL }}"
  dataFrom:
    - extract:
        key: trmnl
