---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/v1alpha1_config.schema.json
machine:
  type: controlplane
  install:
    image: factory.talos.dev/metal-installer/7fe953aa80ac882abc707dad04f849b09b00d4834e50d7368a332e1ce3608a4e:{{ ENV.TALOS_VERSION }}
    diskSelector:
      serial: 2318E6D1E1A3
  kernel:
    modules:
      - name: nbd
      - name: thunderbolt
      - name: thunderbolt_net
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: HostnameConfig
hostname: fenrys
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
# Primary Interface
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr) == "58:47:ca:76:19:1b"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: EthernetConfig
name: enp2s0f0np0
rings:
  rx: 8160
  tx: 8160
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
# Intel vPRO Interface
# We don't want talos to control this interface, just have it up for IPMI access. Intel will manage it's IP.
apiVersion: v1alpha1
kind: LinkAliasConfig
name: ipmi
selector:
  match: link.bus_path == "0000:59:00.0"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: LinkConfig
name: ipmi
up: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: DHCPv4Config
name: ipmi
routeMetric: 4096
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links: [net0]
bondMode: active-backup
mtu: 9000
up: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.30
parent: bond0
vlanID: 30
mtu: 9000
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: LinkAliasConfig
name: shylily
selector:
  match:  link.bus_path == "0-1.0"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: LinkConfig
name: shylily
up: true
mtu: 65520
addresses: [{ address: 169.254.254.10/32 }]
routes: [{ destination: 169.254.254.12/32, metric: 2048 }]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: LinkAliasConfig
name: maomao
selector:
  match: link.bus_path == "1-1.0"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/release-1.12/website/content/v1.12/schemas/config.schema.json
apiVersion: v1alpha1
kind: LinkConfig
name: maomao
up: true
mtu: 65520
addresses: [{ address: 169.254.254.10/32 }]
routes: [{ destination: 169.254.254.11/32, metric: 2048 }]
