---
machine:
  type: controlplane
  install:
    diskSelector:
      serial: 2318E6D1EDC2
  kernel:
    modules:
      - name: thunderbolt
      - name: thunderbolt_net
  network:
    hostname: shylily
    interfaces:
      - deviceSelector: { busPath: 0000:59:00.0 } # Intel IPMI
        ignore: true
      - interface: bond0
        bond:
          deviceSelectors:
            - hardwareAddr: 58:47:ca:7b:ec:1e
              driver: i40e
              physical: true
          mode: active-backup
        dhcp: true
        mtu: 9000
        vip:
          ip: 10.0.10.2
        vlans:
          - # IOT
            vlanId: 30
            dhcp: false
            mtu: 9000
      - deviceSelector: { busPath: 1-1.0 } # Fenrys
        dhcp: false
        mtu: 65520
        addresses: [169.254.254.12/32]
        routes: [{ network: 169.254.254.10/32, metric: 2048 }]
      - deviceSelector: { busPath: 0-1.0 } # Maomao
        dhcp: false
        mtu: 65520
        addresses: [169.254.254.12/32]
        routes: [{ network: 169.254.254.11/32, metric: 2048 }]
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp2s0f0np0
rings:
  rx: 8160
  tx: 8160
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp2s0f1np1
rings:
  rx: 8160
  tx: 8160