---
machine:
  install:
    image: factory.talos.dev/metal-installer/f5b4219136c4be042f25ee55c87d3b45d639e671e58c4c95a227204883e2114b:v1.12.6
    diskSelector:
      serial: 2318E6D1EDC2
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: shylily