---
machine:
  type: controlplane
  install:
    image: factory.talos.dev/metal-installer/f5b4219136c4be042f25ee55c87d3b45d639e671e58c4c95a227204883e2114b:{{ ENV.TALOS_VERSION }}
    diskSelector:
      serial: 2318E6D1804C
  kernel:
    modules:
      - name: nbd
      - name: thunderbolt
      - name: thunderbolt_net
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: maomao
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr) == "58:47:ca:7b:ed:f6"
---
apiVersion: v1alpha1
kind: EthernetConfig
name: net0
rings:
  rx: 8160
  tx: 8160
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: ipmi
selector:
  match: link.bus_path == "0000:59:00.0"
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links: [net0]
bondMode: active-backup
mtu: 9000
up: true
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
---
apiVersion: v1alpha1
kind: DHCPv6Config
name: bond0
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.30
parent: bond0
vlanID: 30
mtu: 9000
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: shylily
selector:
  match:  link.bus_path == "1-1.0"
---
apiVersion: v1alpha1
kind: LinkConfig
name: shylily
up: true
mtu: 65520
addresses: [{ address: 169.254.254.11/32, routePriority: 2048 }]
routes: [{ destination: 169.254.254.10/32 }]
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: fenrys
selector:
  match: link.bus_path == "0-1.0"
---
apiVersion: v1alpha1
kind: LinkConfig
name: fenrys
up: true
mtu: 65520
addresses: [{ address: 169.254.254.11/32, routePriority: 2048 }]
routes: [{ destination: 169.254.254.12/32 }]