---
machine:
  type: controlplane
  install:
    image: factory.talos.dev/metal-installer/36ec35e34832232b3e9c878cc924767b80e2789bc41daa5dc1035caa81ac9d24:v1.13.4
    disk: /dev/sda
  network:
    interfaces:
      - deviceSelector:
          physical: true
        addresses: ["10.0.10.240/24"]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.10.1
        mtu: 9000
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: tuddle
