---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: onepassword-secret
    template:
      data:
        1password-credentials.json: '{{ .op_OP_CREDENTIALS_JSON }}'
        token: '{{ .op_OP_CONNECT_TOKEN }}'
  dataFrom:
    - extract:
        key: 1password
      rewrite:
        - regexp:
            source: "(.*)"
            target: "op_$1"
