---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bluemap
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
        containers:
          bluemap:
            image:
              repository: ghcr.io/bluemap-minecraft/bluemap
              tag: v5.11@sha256:d11a151f52c6b158134226ab7abb8085e4a5c8bb678a91eb6b125d7121918063
            args: "-w" # For initial configuration, use -g"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 0.5
                memory: 1G
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      bluemap:
        controller: minecraft
        ports:
          web:
            port: &web-port 8100
    route:
      bluemap:
        hostnames: ["map.ok8.sh"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *web-port
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /app/data
            subPath: data
      config:
        type: persistentVolumeClaim
        existingClaim: *app
        globalMounts:
          - path: /app/config
            subPath: config
          - path: /app/web
            subPath: web