---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app marianland
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minecraft:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          marianland:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2025.8.1-java21
            env:
              EULA: "true"
              TZ: America/Los_Angeles
              TYPE: "PAPER"
              VERSION: "1.21.8"
              ONLINE_MODE: false
              SERVER_NAME: *app
              DIFFICULTY: easy
              MAX_PLAYERS: 40
              KEEP_INVENTORY: true
              ENABLE_ROLLING_LOGS: true
              ALLOW_FLIGHT: true
              INIT_MEMORY: 1G
              MAX_MEMORY: &max-memory 6G
              MODRINTH_PROJECTS: |
                bluemap
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 2
                memory: *max-memory
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      marianland:
        controller: minecraft
        type: LoadBalancer
        ports:
          #game:
          #  port: &game-port 25565
          #rcon:
          #  port: &rcon-port 25578
          http:
            port: &web-port 8100
    route:
      marianland:
        hostnames: ["map.ok8.sh"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *web-port
            matches:
              - path:
                 type: RegularExpression
                 value: ^/maps/marianland_.*
    persistence:
      tmp:
        type: emptyDir
      data:
        existingClaim: *app
        globalMounts:
          - path: /data