---
collections:
  Adult Swim Originals:
    text_file: /config/collections/originals.txt
    sync_mode: sync
    collection_order: alpha
    summary: Original animated series produced for Adult Swim.
    item_sonarr_tag: adultswim
    sonarr_add_missing: false
