---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/monitoring.coreos.com/probe_v1.json
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices-icmp
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - airgradient.outsideour.casa
        #- puddle.outsideour.casa
        - puddle-ipmi.internal
        - ups.outsideour.casa
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-devices
      action: replace
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/monitoring.coreos.com/probe_v1.json
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: nfs
# spec:
#   jobName: nfs_probe
#   module: tcp_connect
#   prober:
#     url: blackbox-exporter.observability.svc.cluster.local:9115
#   targets:
#     staticConfig:
#       static:
#         - puddle.outsideour.casa:2049
#   metricRelabelings:
#     - targetLabel: service
#       replacement: blackbox-exporter-devices
#       action: replace
# ---
# # yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: slzb
# spec:
#   jobName: slzb_probe
#   module: icmp
#   prober:
#     url: blackbox-exporter-lan.o11y.svc.cluster.local:9115
#   targets:
#     staticConfig:
#       static:
#         - zigbee.outsideour.casa
#   metricRelabelings:
#     - targetLabel: service
#       replacement: blackbox-exporter-lan
#       action: replace