---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    creationPolicy: Owner
    template:
      data:
        adminPassword: "{{ .adminPassword }}"
        adminEmail: "{{ .adminEmail }}"
  dataFrom:
    - extract:
        key: forgejo
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"
