---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app meshtastic-web
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: meshtastic-web
  values:
    controllers:
      meshtastic-web:
        containers:
          app:
            image:
              repository: ghcr.io/meshtastic/web
              tag: latest
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: meshtastic-web
        ports:
          http:
            port: &port 8080
    route:
      app:
        hostnames: ["{{ .Release.Name }}.ok8.sh"]
        parentRefs:
          - name: internal
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
