---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kopia-repository-database
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/mnt/puddle/kubernetes/kopia
    type: Directory
  claimRef:
    namespace: database
    name: kopia-repository
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-repository
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: kopia-repository-database
