---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: recyclarr-secret
    template:
      data:
        RADARR_API_KEY: "{{ .radarr_RADARR_API_KEY }}"
        SONARR_API_KEY: "{{ .sonarr_SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
