---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name ${APP}
spec:
  postgresVersion: 17
  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M
  patroni: # turn on sync writes to at least 1 other replica
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        max_wal_size: 5GB
        synchronous_commit: "on"
        parameters:
          max_connections: 500
  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: ${APP}-crunchy-postgres
      replicas: &replicas 3 # One per node
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
  users:
    # Superuser
    - name: "postgres"
      databases: ["postgres"]
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: "${USERNAME:=${APP}}"
      databases: ${DATABASES:=["${APP}"]}
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: "${APP}-crunchy-postgres"
      global: &backupFlag
        compress-type: "bz2"
        compress-level: "9"
        repo2-block: "y"
        repo2-bundle: "y"
        repo2-path: /${APP}
        repo2-retention-full: "7" # days
        repo2-retention-full-type: time
        repo2-s3-uri-style: path
      jobs:
        ttlSecondsAfterFinished: 60
      manual:
        repoName: repo2
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: ${APP}-crunchy-postgres-backup
      repos:
        - name: repo2
          s3: &s3
            bucket: crunchy-pgo
            endpoint: https://3ed51f2c99510cd7fe8fcd8ed0621a37.r2.cloudflarestorage.com/crunchy-postgres
            region: us-east-1 # https://developers.cloudflare.com/r2/api/s3/api/#bucket-region
          schedules:
            full: "30 2 * * 0" # Sunday at 02:30
            incremental: "30 2 * * 1-6/2" # Mon-Sat at 02:30, every 2nd day
  dataSource:
    pgbackrest:
      stanza: db
      configuration: *backupConfig
      global: *backupFlag
      repo:
        name: repo2
        s3: *s3
  proxy:
    pgBouncer:
      port: 5432
      # replicas: 1
      config:
        global:
          pool_mode: ${POOL_MODE:=session}
          client_tls_sslmode: prefer
          default_pool_size: "100"
          max_client_conn: "500"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: ${APP}-pgbouncer