---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-apps
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./apirouter/ks.yaml
  - ./home-assistant-api/ks.yaml
  - ./ok8-sh/ks.yaml
  - ./trmnl/ks.yaml
