---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  apply-node:
    desc: Apply Talos config to a node [NODE=required]
    dotenv: ["{{.TALOS_DIR}}/talos.env"]
    cmd: |-
      minijinja-cli "{{.TALOS_DIR}}/machineconfig.yaml.j2" \
      | op inject \
      | talosctl --nodes "{{.NODE}}" apply-config \
          --mode "{{.MODE}}" \
          --config-patch @<(minijinja-cli "{{.TALOS_DIR}}/nodes/{{.NODE}}.yaml") \
          --config-patch @"{{.TALOS_DIR}}/patches/logging.yaml" \
          --file /dev/stdin \
          {{if .INSECURE}}--insecure{{end}}

    vars:
      MODE: '{{.MODE | default "auto"}}'
      INSECURE:
        sh: talosctl --nodes {{.NODE}} get machineconfig &> /dev/null || echo true
      MACHINE_TYPE:
        sh: |-
          talosctl --nodes {{.NODE}} get machinetypes --output=jsonpath='{.spec}' 2> /dev/null \
            || basename $(find '{{.TALOS_DIR}}' -name '{{.NODE}}.yaml' -printf '%h')
    env:
      MACHINE_TYPE: '{{.MACHINE_TYPE}}'
    requires:
      vars: [NODE]
    preconditions:
      - op user get --me
      - talosctl config info
      - test -f {{.TALOS_DIR}}/talos.env
      - test -f {{.TALOS_DIR}}/machineconfig.yaml.j2
      - test -f {{.TALOS_DIR}}/nodes/{{.NODE}}.yaml
      - test -f {{.TALOS_DIR}}/talosconfig
      - which minijinja-cli talosctl

  upgrade-node:
    desc: Upgrade Talos on a single node [NODE=required]
    cmd: talosctl --nodes {{.NODE}} upgrade --image={{.TALOS_IMAGE}} --force
    vars:
      MACHINE_TYPE:
        sh: talosctl --nodes {{.NODE}} get machinetypes --output=jsonpath='{.spec}'
      TALOS_IMAGE:
        sh: |-
          talosctl --nodes {{.NODE}} get machineconfig --output=jsonpath='{.spec}' \
            | yq '.machine.install.image | select(. != null)'
    requires:
      vars: [NODE]
    preconditions:
      - talosctl config info
      - talosctl --nodes {{.NODE}} get machineconfig
      - which minijinja-cli talosctl yq

  upgrade-k8s:
    desc: Upgrade Kubernetes across the whole cluster [VERSION=required]
    dotenv: ["{{.TALOS_DIR}}/talos.env"]
    cmds:
      - talosctl --nodes {{.TALOS_CONTROLLER}} upgrade-k8s --to $KUBERNETES_VERSION
      - talosctl health --wait-timeout=10m --server=false
    vars:
      TALOS_CONTROLLER:
        sh: talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1
    preconditions:
      - curl -fsSL -o /dev/null --fail https://github.com/siderolabs/kubelet/releases/tag/$KUBERNETES_VERSION
      - talosctl --nodes {{.TALOS_CONTROLLER}} get machineconfig
      - talosctl config info
      - test -f {{.TALOS_DIR}}/talos.env
      - which jq talosctl

  reset-node:
    desc: Reset Talos on a single node [NODE=required]
    prompt: Reset Talos node '{{.NODE}}' ... continue?
    cmd: talosctl reset --nodes {{.NODE}} --graceful=false
    requires:
      vars: [NODE]
    preconditions:
      - talosctl --nodes {{.NODE}} get machineconfig
      - talosctl config info
      - which talosctl

  reset-cluster:
    desc: Reset Talos across the whole cluster
    prompt: Reset Talos  ... continue?
    cmd: talosctl reset --nodes {{.NODE_ADDRS}} --graceful=false
    vars:
      NODE_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(",")'
    preconditions:
      - talosctl --nodes {{.NODE_ADDRS}} get machineconfig
      - talosctl config info
      - which jq talosctl

  apply-cluster:
    desc: Apply Talos config across the whole cluster [MODE=default]
    cmds:
      - for: { var: NODE_ADDRS }
        task: apply-node
        vars:
          NODE: "{{.ITEM}}"
          MODE: "{{.MODE}}"
    vars:
      MODE: '{{.MODE | default "auto"}}'
      NODE_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl

  upgrade-cluster:
    desc: Upgrade Talos across the whole cluster
    cmds:
      - for: { var: NODE_ADDRS }
        task: upgrade-node
        vars:
          NODE: "{{.ITEM}}"
    vars:
      NODE_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl

  reboot-cluster:
    desc: Reboot Talos on a single node [NODE=required] [MODE=default]
    cmds:
      - for: { var: NODE_ADDRS }
        task: reboot-node
        vars:
          NODE: "{{.ITEM}}"
          MODE: "{{.MODE}}"
    vars:
      NODE_ADDRS:
        sh: talosctl config info --output json | jq --join-output '[.nodes[]] | join(" ")'
    preconditions:
      - which jq talosctl
