---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: b2
spec:
  allowedNamespaces:
    all: true
  backend:
    b2:
      bucket: puddle-kopia
      prefix: kopiur/
      auth:
        secretRef:
          name: kopiur-repository-secret
          namespace: kopiur-system
  encryption:
    passwordSecretRef:
      name: kopiur-repository-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
