---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-repository-secret
  data:
    - secretKey: B2_KEY_ID
      remoteRef:
        key: kopiur
        property: B2_KEY_ID
    - secretKey: B2_KEY
      remoteRef:
        key: kopiur
        property: B2_KEY
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: kopiur
        property: KOPIA_PASSWORD
