---
originRequest:
  originServerName: "external.ok8.sh"

ingress:
  - hostname: "ok8.sh"
    service: https://envoy-external.networking.svc.cluster.local
  - hostname: "*.ok8.sh"
    service: https://envoy-external.networking.svc.cluster.local
  - service: http_status:404
