---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apis
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: apis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # TRMNL private plugin webhook URLs.
        TRMNL_TEXT_WEBHOOK_URL: "{{ .trmnl_TRMNL_TEXT_WEBHOOK_URL }}"
        TRMNL_IMAGE_WEBHOOK_URL: "{{ .trmnl_TRMNL_IMAGE_WEBHOOK_URL }}"
        HOME_ASSISTANT_BASE_URL: "http://home-assistant.default.svc.cluster.local:8123"
        HOME_ASSISTANT_TOKEN: "{{ .home_assistant_api_HOME_ASSISTANT_TOKEN }}"
        HOME_ASSISTANT_LIGHT_GROUP: "{{ .home_assistant_api_HOME_ASSISTANT_LIGHT_GROUP }}"
        SPOTIFY_CLIENT_ID: "{{ .spotify_SPOTIFY_CLIENT_ID }}"
        SPOTIFY_CLIENT_SECRET: "{{ .spotify_SPOTIFY_CLIENT_SECRET }}"
        SPOTIFY_REDIRECT_URI: "https://api.ok8.sh/spotify/setup"
        REDIS_URL: "redis://dragonfly.custom-apps.svc.cluster.local:6379/0"
        GITHUB_USERNAME: "kashalls"
        GITHUB_TOKEN: "{{ .ok8_sh_NUXT_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: trmnl
      rewrite:
        - regexp:
            source: "(.*)"
            target: "trmnl_$1"
    - extract:
        key: home-assistant-api
      rewrite:
        - regexp:
            source: "(.*)"
            target: "home_assistant_api_$1"
    - extract:
        key: spotify
      rewrite:
        - regexp:
            source: "(.*)"
            target: "spotify_$1"
    - extract:
        key: github
      rewrite:
        - regexp:
            source: "(.*)"
            target: "github_$1"
    - extract:
        key: ok8-sh
      rewrite:
        - regexp:
            source: "(.*)"
            target: "ok8_sh_$1"
