---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apis
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: apis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # TRMNL private plugin webhook URLs.
        TRMNL_TEXT_WEBHOOK_URL: "{{ .TRMNL_TEXT_WEBHOOK_URL }}"
        TRMNL_IMAGE_WEBHOOK_URL: "{{ .TRMNL_IMAGE_WEBHOOK_URL }}"
        HOME_ASSISTANT_BASE_URL: "http://home-assistant.default.svc.cluster.local:8123"
        HOME_ASSISTANT_TOKEN: "{{ .HOME_ASSISTANT_TOKEN }}"
        HOME_ASSISTANT_LIGHT_GROUP: "{{ .HOME_ASSISTANT_LIGHT_GROUP }}"
        SPOTIFY_CLIENT_ID: "{{ .SPOTIFY_CLIENT_ID }}"
        SPOTIFY_CLIENT_SECRET: "{{ .SPOTIFY_CLIENT_SECRET }}"
        SPOTIFY_REDIRECT_URI: "https://api.ok8.sh/api/spotify/setup"
        REDIS_URL: "redis://dragonfly.custom-apps.svc.cluster.local:6379/0"
        GITHUB_USERNAME: "kashalls"
        GITHUB_TOKEN: "{{ .NUXT_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: trmnl
    - extract:
        key: home-assistant-api
    - extract:
        key: spotify
    - extract:
        key: github
    - extract:
        key: ok8-sh
