---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: matter
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      matter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/matter-js/python-matter-server:8.1.2
              tag: 8.1.2@sha256:6827e352011e2d8c2bde771e446fcf72acc49150ef66bad978816bac1762aad3
            env:
              TZ: America/Los_Angeles
              MATTER_SERVER__INSTANCE_NAME: "{{ .Release.Name }}"
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host "{{ .Release.Name }}.ok8.sh"
              MATTER_SERVER__LOG_LEVEL: info
            args:
              - --storage-path=/data
              - --primary-interface=net1
              - --log-level=debug
              - --log-level-sdk=info
            resources:
              limits:
                memory: 256Mi
    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "iot",
            "namespace": "networking",
            "ips": ["10.0.30.23/24"]
          }]
      hostUsers: false
      securityContext:
        runAsNonRoot: false # Must be run as root user
        runAsUser: 0 # Must be run as root user
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 34
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - *host
        parentRefs:
          - name: envoy-internal
            namespace: networking
        rules:
          - backendRefs:
              - name: "{{ .Release.Name }}"
                port: *port
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir