---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-secret
    template:
      data:
        SABNZBD__API_KEY: &apiKey "{{ .sabnzbd_SABNZBD_API_KEY }}"
        SABNZBD__NZB_KEY: *apiKey
        CROSS_SEED_API_KEY: "{{ .cross_seed_CROSS_SEED_API_KEY }}"
  dataFrom:
    - extract:
        key: sabnzbd
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sabnzbd_$1"
    - extract:
        key: cross-seed
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cross_seed_$1"
