---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app acars
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      acars-decoder-1:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_0bda_2838_00000001.present: "true"
        containers:
          acars-decoder:
            image:
              repository: ghcr.io/sdr-enthusiasts/docker-acarsdec
              tag: latest-build-412
            env:
              FEED_ID: KASHUWU-ACARS-1
              DEVICE: "00000001"
              TZ: Etc/UTC
              SOAPYSDR: driver=rtlsdr,serial=$(DEVICE)
              FREQUENCIES: "131.725;131.550;131.425;131.125"
              # Enabling all frequencies to determine which are actually used
              # RTL-SDR can only scan 2MHz range
              # See https://app.airframes.io/about
              # FREQUENCIES: >-
              #   130.025;130.425;130.450;130.825;130.850;131.125;131.425;
              #   131.450;131.475;131.525;131.550;131.725;131.825;131.850
              OUTPUT_SERVER: acars-acars-router
              OUTPUT_SERVER_PORT: "5550"
              OUTPUT_SERVER_MODE: tcp
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 150m
                memory: 64Mi
              limits:
                cpu: 1
                memory: 128Mi
      acars-decoder-2:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_0bda_2838_00000002.present: "true"
        containers:
          acars-decoder:
            image:
              repository: ghcr.io/sdr-enthusiasts/docker-acarsdec
              tag: latest-build-412
            env:
              FEED_ID: KASHUWU-ACARS-2
              DEVICE: "00000002"
              TZ: Etc/UTC
              SOAPYSDR: driver=rtlsdr,serial=$(DEVICE)
              FREQUENCIES: "130.025;130.450;130.825"
              # Enabling all frequencies to determine which are actually used
              # RTL-SDR can only scan 2MHz range
              # See https://app.airframes.io/about
              # FREQUENCIES: >-
              #   130.025;130.425;130.450;130.825;130.850;131.125;131.425;
              #   131.450;131.475;131.525;131.550;131.725;131.825;131.850
              OUTPUT_SERVER: acars-acars-router
              OUTPUT_SERVER_PORT: "5550"
              OUTPUT_SERVER_MODE: tcp
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 150m
                memory: 64Mi
              limits:
                cpu: 1
                memory: 128Mi
      dumpvdl2:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            feature.node.kubernetes.io/usb-ff_0bda_2838_00000003.present: "true"
        replicas: 1
        containers:
          dumpvdl2:
            securityContext:
              privileged: true
            image:
              repository: ghcr.io/sdr-enthusiasts/docker-dumpvdl2
              tag: latest-build-348
            env:
              FEED_ID: KASHUWU-VDL2-1
              DEVICE: "00000003"
              TZ: Etc/UTC
              SOAPYSDR: driver=rtlsdr,serial=$(DEVICE)
              # See https://app.airframes.io/about
              # See also https://gist.github.com/tyzbit/8df46263085b0f3d9e2dd09069438f89
              FREQUENCIES: 136.650;136.975;136.800;136.100;136.675
              ZMQ_MODE: client
              ZMQ_ENDPOINT: tcp://acars-acars-router:35555
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
      acars-router:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          acars-router:
            image:
              repository: ghcr.io/sdr-enthusiasts/acars_router
              tag: 1.3.1_linux_amd64
            env:
              TZ: Etc/UTC
              AR_SEND_UDP_ACARS: acars-acars-hub:5550;feedthe.acarsdrama.com:5550 #;feed.acars.io:5550
              AR_SEND_UDP_VDLM2: acars-acars-hub:5555;feedthe.acarsdrama.com:5555 #;feed.airframes.io:5552
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 96Mi
      acars-hub:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          acars-hub:
            image:
              repository: ghcr.io/sdr-enthusiasts/docker-acarshub
              tag: v3.8.0Build1379_nohealthcheck
            env:
              TZ: Etc/UTC
              ENABLE_ADSB: "false"
              ENABLE_ACARS: external
              ENABLE_VDLM: external
              QUIET_MESSAGES: "false" # This logs the messages themselves
            resources:
              requests:
                cpu: 300m
                memory: 192Mi
              limits:
                memory: 256Mi
    service:
      acars-router:
        controller: acars-router
        ports:
          acars:
            port: 5550
          vdlm2-zmq:
            port: 35555
      dumpvdl2:
        controller: dumpvdl2
        type: ClusterIP
        ports:
          vdlm2:
            port: 5555
          vdlm2-zmq:
            port: 45555
      acars-hub:
        controller: acars-hub
        ports:
          http:
            port: &port 80
          acarsinput:
            port: 5550
            protocol: UDP
          vdslinput:
            port: 5555
            protocol: UDP
          acarsoutput:
            port: 15550
          vdsloutput:
            port: 15555
    route:
      app:
        hostnames: ["{{ .Release.Name }}.ok8.sh"]
        parentRefs:
          - name: internal
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - name: acars-hub
                port: *port
    persistence:
      acars-hub:
        type: persistentVolumeClaim
        storageClass: ceph-block
        size: 2G
        accessMode: ReadWriteOnce
        advancedMounts:
          acars-hub:
            acars-hub:
              - path: /run/acars
