apiVersion: v1
kind: ServiceAccount
metadata:
  name: acars-usb-watchdog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acars-usb-watchdog
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets/scale", "statefulsets"]
  verbs: ["get", "list", "update", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acars-usb-watchdog
  namespace: default
subjects:
- kind: ServiceAccount
  name: acars-usb-watchdog
  namespace: default
roleRef:
  kind: Role
  name: acars-usb-watchdog
  namespace: default
  apiGroup: rbac.authorization.k8s.io