---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./echo/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./multus/ks.yaml
  - ./unifi-dns/ks.yaml
