---
apiVersion: v1
spec:
  containers:
    - name: debug
      image: docker.io/library/alpine:latest
      command: ["/bin/sh", "-c", "apk add --no-cache zfs && exec /bin/sh"]
      stdin: true
      stdinOnce: true
      tty: true
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
      volumeMounts:
        - mountPath: /var/mnt/puddle
          name: puddle
          mountPropagation: HostToContainer
        - mountPath: /dev/zfs
          name: zfs
  dnsPolicy: ClusterFirstWithHostNet
  hostIPC: true
  hostNetwork: true
  hostPID: true
  nodeName: ${NODE}
  restartPolicy: Never
  volumes:
    - name: puddle
      hostPath:
        path: /var/mnt/puddle
    - name: zfs
      hostPath:
        path: /dev/zfs
