---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kopia-b2
  namespace: &namespace volsync-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/volsync-system/kopia-b2/app
  prune: true
  retryInterval: 1m
  targetNamespace: *namespace
  timeout: 5m
  wait: true
