---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: waifulabs-app-private-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: waifulabs-app-private-key
    template:
      data:
        # github_token: "{{ .RUNNER_TOKEN }}"
        github_app_id: "{{ .APP_ID }}"
        github_app_installation_id: "{{ .INSTALLATION_ID }}"
        github_app_private_key: "{{ .PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: waifuz-bot

---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: renovate-waifulabs-github-token
spec:
  appID: "1790271"
  installID: "81194784"
  auth:
    privateKey:
      secretRef:
        name: waifulabs-app-private-key
        key: github_app_private_key
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-waifulabs-github-token
spec:
  refreshInterval: "30m0s"
  target:
    name: renovate-waifulabs-github-token
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_USER: d2FpZnVsYWJzCg==
        GITHUB_COM_TOKEN: "{{ .token }}"
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: renovate-waifulabs-github-token
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: waifulabs
spec:
  discoveryFilter: waifulabs/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_REDIS_URL
      value: redis://renovate-dragonfly.renovate.svc.cluster.local:6379
    - name: RENOVATE_CONFIG
      value: '{"extends":["config:recommended","docker:enableMajor","helpers:pinGitHubActionDigests",":automergeBranch",":disableRateLimiting",":dependencyDashboard",":semanticCommits",":timezone(America/Los_Angeles)"],"dependencyDashboardTitle":"Renovate Dashboard 🗡️","suppressNotifications":["prEditedNotification","prIgnoreNotification"]}'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_INTERNAL_CHECKS_FILTER
      value: strict
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  extraVolumeMounts:
    - name: cache
      mountPath: /cache
  extraVolumes:
    - name: cache
      persistentVolumeClaim:
        claimName: renovate-cache
  image: ghcr.io/renovatebot/renovate:43.104.6
  parallelism: 5
  provider:
    name: github
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-waifulabs-github-token
  skipForks: true
  webhook:
    enabled: true
    authentication:
      enabled: false