---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: true
spec:
  postgresVersion: 17
  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        max_wal_size: 5GB
        synchronous_commit: "on"
        parameters:
          max_connections: 500
  instances:
    - name: &instance-name postgres
      metadata:
        labels:
          app.kubernetes.io/name: *name
      replicas: &replicas 3
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: *name
                postgres-operator.crunchydata.com/instance-set: *instance-name
  users:
    # Superuser
    - name: "postgres"
      databases: ["postgres"]
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: "bluemap"
      databases: ["bluemap"]
      password:
        type: AlphaNumeric
    - name: "sunlight"
      databases: ["sunlight"]
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: postgres-secret
      global: &backupFlag
        compress-type: "bz2"
        compress-level: "9"
        repo2-block: "y"
        repo2-bundle: "y"
        repo2-path: /
        repo2-retention-full: "7" # days
        repo2-retention-full-type: time
        repo2-s3-uri-style: path
      jobs:
        ttlSecondsAfterFinished: 60
      manual:
        repoName: repo2
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: "postgres-backup"
      repos:
        - name: repo2
          s3: &s3
            bucket: super-awesome-postgres
            endpoint: s3.us-west-004.backblazeb2.com
            region: us-west-004
          schedules:
            full: "30 2 * * 0" # Sunday at 02:30
            incremental: "30 2 * * 1-6/2" # Mon-Sat at 02:30, every 2nd day
  #dataSource:
  # pgbackrest:
  #    stanza: db
  #    configuration: *backupConfig
  #    global: *backupFlag
  #    repo:
  #      name: repo2
  #      s3: *s3
  proxy:
    pgBouncer:
      port: 5432
      replicas: 2
      config:
        global:
          pool_mode: session
          client_tls_sslmode: prefer
          default_pool_size: "100"
          max_client_conn: "500"
      service:
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/target: "postgres.ok8.sh"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/role: "postgres-bouncer"