---
# yaml-language-server: $schema=https://kube-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-secret
    template:
      data:
        s3.conf: |
          [global]
          repo2-s3-key={{ .AWS_ACCESS_KEY_ID }}
          repo2-s3-key-secret={{ .AWS_SECRET_ACCESS_KEY }}
        encryption.conf: |
          [global]
          repo2-cipher-pass={{ .ENCRYPTION_KEY }}
  dataFrom:
    - extract:
        key: backblaze