---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./podmonitor.yaml
patches:
  - patch: |-
      - op: remove
        path: /spec/dataSource
    target:
      kind: PostgresCluster