router bgp 64513
  bgp router-id 10.0.10.1
  no bgp ebgp-requires-policy
  no bgp default ipv4-unicast
  no bgp network import-check

  neighbor k8s-puddle peer-group
  neighbor k8s-puddle remote-as 64514
  ! These are agressive timers, you might want to double those values
  ! neighbor k8s-puddle timers 2 6
  ! neighbor k8s-puddle timers connect 5
  neighbor k8s-puddle activate
  ! neighbor k8s-puddle soft-reconfiguration inbound

  neighbor k8s-sable peer-group
  neighbor k8s-sable remote-as 64515
  neighbor k8s-sable activate

  neighbor 10.0.10.2 peer-group k8s-puddle
  neighbor 10.0.10.3 peer-group k8s-sable

  address-family ipv4 unicast
    neighbor k8s-puddle next-hop-self
    neighbor k8s-puddle activate
    neighbor k8s-sable next-hop-self
    neighbor k8s-sable activate
  exit-address-family

