---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kopia-repository-matrix
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/mnt/apps/kubernetes/kopia
    type: Directory
  claimRef:
    namespace: matrix
    name: kopia-repository
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-repository
  namespace: matrix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: kopia-repository-matrix
