---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immichframe-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        immich_api_key: "{{ .token }}"
        ssh_private_key: "{{ .private_key }}"
  dataFrom:
    - extract:
        key: immich-frame
    - extract:
        key: frame
