---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tofu-controller
spec:
  interval: 1h
  url: https://flux-iac.github.io/tofu-controller
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name tofu-controller
spec:
  interval: 1h
  releaseName: *name
  targetNamespace: flux-system
  chart:
    spec:
      chart: tofu-controller
      version: ">=0.16.2"
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicaCount: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 128Mi
    image:
      tag: v0.16.2
    runner:
      image:
        tag: v0.16.2
