---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-frame
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-frame-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ApiKey: "{{ .token }}"
  dataFrom:
    - extract:
        key: immich-frame
