---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: waifu-gateway-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: waifu-gateway-secret
    template:
      engineVersion: v2
      data:
        DISCORD_TOKEN: "{{ .discord_token }}"
  dataFrom:
    - extract:
        key: waifu-discord
      rewrite:
        - regexp:
            source: "(.*)"
            target: "discord_$1"
