---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  values:
    controllers:
      immich:
        strategy: RollingUpdate
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.2.1@sha256:2c951a4063b55ec2de197fdf6a85e32b05872d3a18a18eaf851b827ff2622814
            env:
              TZ: "America/Los_Angeles"
              IMMICH_TRUSTED_PROXIES: "172.31.0.0/16"
              IMMICH_MEDIA_LOCATION: &mediaLocation /library
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: pgbouncer-uri
              REDIS_HOSTNAME: &redisHostname "immich-valkey.default.svc.cluster.local"
              IMMICH_TELEMETRY_INCLUDE: "all"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 6G
      machine-learning:
        strategy: RollingUpdate
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.2.1@sha256:590a76bba3d88ccf78b03cde0c0fb8788f7d76ae6caf90ad33a34b5b4cc35f11
            env:
              REDIS_HOSTNAME: *redisHostname
              MPLCONFIGDIR: "/cache/matplotlib"
              IMMICH_MEDIA_LOCATION: *mediaLocation
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4G
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &mlPort 3003
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *mlPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 60
      valkey:
        containers:
          app:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 9.0.0
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec: &probe-exec { command: ["sh", "-c", "valkey-cli ping | grep PONG"] }
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  exec: *probe-exec
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  exec: *probe-exec
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
    service:
      immich:
        controller: immich
        ports:
          http:
            port: &port 2283
          metrics-api:
            port: 8081
          metrics-ms:
            port: 8082
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: *mlPort
      valkey:
        controller: valkey
        ports:
          http:
            port: 6379
    serviceMonitor:
      immich:
        enabled: true
        serviceName: immich
        endpoints:
          - port: metrics-api
            scheme: http
            path: /metrics
          - port: metrics-ms
            scheme: http
            path: /metrics
    route:
      immich:
        hostnames: ["photos.ok8.sh"]
        parentRefs:
          - name: external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - name: immich
                port: *port
    persistence:
      matplotlib:
        type: emptyDir
        advancedMounts:
          immich:
            main:
              - path: /config/matplotlib
      library:
        type: nfs
        server: fran.outsideour.casa
        path: /mnt/loki/immich
        globalMounts:
          - path: *mediaLocation
      cache:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          machine-learning:
            main:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache
      tmpfs:
        type: emptyDir
        advancedMounts:
          immich:
            main:
              - path: /usr/src/app/.reverse-geocoding-dump
                subPath: geocoding
              - path: /usr/src/app/.transformers_cache
                subPath: transformers
