---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/storage.k8s.io/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-zfs
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-zfs-luddle
