---
machine:
  type: controlplane
  install:
    image: factory.talos.dev/metal-installer/523a9681bdc9722734e5ea7c44f8bf35e250376ef71b14114c59572fffa2dddd:v1.13.2
    diskSelector:
      serial: 50026B7382F40A20
  nodeTaints:
    kubernetes.io/arch: arm64:NoSchedule
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: nyanners
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr) == "38:05:25:34:16:05"
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links: [net0]
bondMode: active-backup
mtu: 9000
up: true
