---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backendtrafficpolicy.yaml
  - ./certificate.yaml
  - ./clienttrafficpolicy.yaml
  - ./envoyproxy.yaml
  - ./gateway.yaml
  - ./external.yaml
  - ./internal.yaml
  - ./redirect.yaml