---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-luddle
provisioner: zfs.csi.openebs.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  poolname: "luddle"
  fstype: "zfs"
