---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
  labels:
    thisisstupid.ok8.sh: external
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  endpoints:
    - dnsName: external.ok8.sh
      recordType: CNAME
      targets: ["edge-na.towonel.dev"]
