---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-agent-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: towonel-agent-secret
    creationPolicy: Owner
  data:
    - secretKey: TOWONEL_INVITE_TOKEN
      remoteRef:
        key: towonel-tunnel
        property: invite_token
