---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: towonel-agent
spec:
  chartRef:
    kind: OCIRepository
    name: towonel-agent
  interval: 1h
  values:
    replicaCount: 2
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    agent:
      logLevel: info
      healthPort: 9090
      services:
        - hostname: "*.ok8.sh"
          origin: envoy-external.networking.svc.cluster.local:443
      inviteTokenSecret:
        name: towonel-agent-secret
        key: TOWONEL_INVITE_TOKEN
    monitoring:
      serviceMonitor:
        enabled: true
        interval: 1m
      prometheusRule:
        enabled: true
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          allowCrossNamespaceImport: true
          matchLabels:
            grafana.internal/instance: grafana
